/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author hp
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    
    private IGameCallback callback;
    private int PlayerPoints;
    private int GameDuration;
    private ArrayList<Wall> walls;
    private Player playerInst;
    
    private Timer gameTimer, wallsUpdateCoords, wallsUpdateLocation;
    
    public Game(int duration) {
        initComponents();
        
        GameDuration = duration; // 20 seconds
        
        InitializeGameComponents();
        WallMovement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayerObj = new javax.swing.JButton();
        WallObj1 = new javax.swing.JButton();
        WallObj3 = new javax.swing.JButton();
        WallObj4 = new javax.swing.JButton();
        WallObj2 = new javax.swing.JButton();
        WallObj5 = new javax.swing.JButton();
        WallObj6 = new javax.swing.JButton();
        WallObj7 = new javax.swing.JButton();
        WallObj8 = new javax.swing.JButton();
        GoalObj = new javax.swing.JButton();
        GameMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EndGameMenuItem = new javax.swing.JMenuItem();
        GameMenu = new javax.swing.JMenu();
        s20TimerMenuItem = new javax.swing.JMenuItem();
        s40TimerMenuItem = new javax.swing.JMenuItem();
        s60TimerMenuItem = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        GameHelpMenuItem = new javax.swing.JMenuItem();
        VersionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game");
        setResizable(false);

        PlayerObj.setBackground(new java.awt.Color(0, 204, 255));
        PlayerObj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PlayerObjKeyPressed(evt);
            }
        });

        WallObj1.setForeground(new java.awt.Color(153, 153, 153));

        WallObj3.setForeground(new java.awt.Color(153, 153, 153));

        WallObj4.setForeground(new java.awt.Color(153, 153, 153));

        WallObj2.setForeground(new java.awt.Color(153, 153, 153));

        WallObj5.setForeground(new java.awt.Color(153, 153, 153));

        WallObj6.setForeground(new java.awt.Color(153, 153, 153));

        WallObj7.setForeground(new java.awt.Color(153, 153, 153));

        WallObj8.setForeground(new java.awt.Color(153, 153, 153));

        GoalObj.setBackground(new java.awt.Color(51, 255, 51));

        FileMenu.setText("File");

        EndGameMenuItem.setText("End Game");
        EndGameMenuItem.setToolTipText("");
        EndGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndGameMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(EndGameMenuItem);

        GameMenuBar.add(FileMenu);

        GameMenu.setText("Game");

        s20TimerMenuItem.setText("20 second Timer");
        s20TimerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s20TimerMenuItemActionPerformed(evt);
            }
        });
        GameMenu.add(s20TimerMenuItem);

        s40TimerMenuItem.setText("40 second Timer");
        s40TimerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s40TimerMenuItemActionPerformed(evt);
            }
        });
        GameMenu.add(s40TimerMenuItem);

        s60TimerMenuItem.setText("60 second Timer");
        s60TimerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s60TimerMenuItemActionPerformed(evt);
            }
        });
        GameMenu.add(s60TimerMenuItem);

        GameMenuBar.add(GameMenu);

        HelpMenu.setText("Help");

        GameHelpMenuItem.setText("Game Help");
        GameHelpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameHelpMenuItemActionPerformed(evt);
            }
        });
        HelpMenu.add(GameHelpMenuItem);

        VersionMenuItem.setText("Version");
        VersionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VersionMenuItemActionPerformed(evt);
            }
        });
        HelpMenu.add(VersionMenuItem);

        GameMenuBar.add(HelpMenu);

        setJMenuBar(GameMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WallObj1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(366, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WallObj8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PlayerObj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(WallObj2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(GoalObj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(WallObj3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(WallObj5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WallObj4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(WallObj7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(WallObj6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WallObj1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WallObj4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(WallObj6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PlayerObj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WallObj2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(WallObj8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(WallObj5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(WallObj3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addComponent(WallObj7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(GoalObj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlayerObjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlayerObjKeyPressed
        // TODO add your handling code here:
        
        int keyCode = evt.getKeyCode();
        int movSpd = playerInst.getCurrMovSpd();
        
        int x = PlayerObj.getLocation().x;
        int y = PlayerObj.getLocation().y;

        switch(keyCode) {
            case KeyEvent.VK_UP:
                y -= movSpd;
                break;
            case KeyEvent.VK_DOWN:
                y += movSpd;
                break;
            case KeyEvent.VK_LEFT:
                x -= movSpd;
                break;
            case KeyEvent.VK_RIGHT:
                x += movSpd;
                break;
        }

        playerInst.setDirLastMoved(
                new Coords(
                    PlayerObj.getLocation().x - x,
                    PlayerObj.getLocation().y - y
                )
        );
        
        PlayerObj.setLocation(x, y);
        
        // Check For Collisions
        PlayerCollision();
    }//GEN-LAST:event_PlayerObjKeyPressed

    private void GameHelpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameHelpMenuItemActionPerformed
        // TODO add your handling code here:
        String helpStr = "";
        
        helpStr += " This is A Game \n\n";
        helpStr += " Use Arrow Keys To Move \n";
        helpStr += " Hover Mouse To Moving Wall to Make it Stop \n";
        helpStr += " Touch the Green Button To Earn Points \n";
        
        JOptionPane.showMessageDialog(rootPane, helpStr);
    }//GEN-LAST:event_GameHelpMenuItemActionPerformed

    private void VersionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VersionMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VersionMenuItemActionPerformed

    private void s20TimerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s20TimerMenuItemActionPerformed
        // TODO add your handling code here:
        
        // Relaunch App with new settings
        callback.RestartGame(20_000);
    }//GEN-LAST:event_s20TimerMenuItemActionPerformed

    private void s40TimerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s40TimerMenuItemActionPerformed
        // TODO add your handling code here:
        
        // Relaunch App with new settings
        callback.RestartGame(40_000);
    }//GEN-LAST:event_s40TimerMenuItemActionPerformed

    private void s60TimerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s60TimerMenuItemActionPerformed
        // TODO add your handling code here:
        
        // Relaunch App with new settings
        callback.RestartGame(60_000);
    }//GEN-LAST:event_s60TimerMenuItemActionPerformed

    private void EndGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndGameMenuItemActionPerformed
        // TODO add your handling code here:
        
        callback.GameFinished(GameDuration, PlayerPoints);
    }//GEN-LAST:event_EndGameMenuItemActionPerformed

    // ==============================================================================
    
    private void InitializeGameComponents() {
        PlayerPoints = 0;
        
        InitTimers();
        
        gameTimer.setRepeats(false);
        gameTimer.start();
        
        playerInst = new Player(5, 5);
        
        walls = new ArrayList<>(Arrays.asList(
                new Wall(WallObj1, new Coords(0, -5)),
                new Wall(WallObj2, new Coords(0, 5)),
                new Wall(WallObj3, new Coords(5, 0)),
                new Wall(WallObj4, new Coords(5, 0)),
                new Wall(WallObj5, new Coords(0, 5)),
                new Wall(WallObj6, new Coords(0, 5)),
                new Wall(WallObj7, new Coords(-5, 0)),
                new Wall(WallObj8, new Coords(5, 0))
        ));
        
        for (Wall wall : walls) {
            wall.getWallObj().addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    //
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    //
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    //
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    wall.setCoords(new Coords(0, 0));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    wall.ResetMoveCoords();
                }
            });
        }
    }
    
    private void InitTimers() {
        gameTimer = new Timer(GameDuration, evt -> {
            callback.GameFinished(GameDuration, PlayerPoints);
        });
        
        wallsUpdateCoords = new Timer(2000, evt -> {
            for (Wall wall : walls) {
                wall.getCoords().x *= -1;
                wall.getCoords().y *= -1;
            }
        });
        
        wallsUpdateLocation = new Timer(100, evt -> {
            for (Wall wall : walls) {
                wall.getWallObj().setLocation(
                    wall.getWallObj().getLocation().x + wall.getCoords().x,
                    wall.getWallObj().getLocation().y + wall.getCoords().y
                );
                
                WallCollision(wall);
            }
        });
    }
    
    private void PlayerCollision() {
        if (PlayerObj.getBounds().intersects(GoalObj.getBounds())) {
            // Add Points To Player
            PlayerPoints += 10;
            
            // Select Random Coord within Frame
            GoalObj.setLocation(
                    new Random().nextInt(this.getSize().width-50),
                    new Random().nextInt(this.getSize().height-100)
            );
        }
        
        CommonCollisions();
    }
    
    private void WallMovement() {
        wallsUpdateCoords.start();
        wallsUpdateLocation.start();
    }
    
    private void WallCollision(Wall wall) {
        if (wall.getWallObj().getBounds().getMinX() < 0) {
            wall.getWallObj().setLocation(this.getSize().width-40, wall.getWallObj().getLocation().y);
        }
        
        if (wall.getWallObj().getBounds().getMaxX() > this.getSize().width) {
            wall.getWallObj().setLocation(5, wall.getWallObj().getLocation().y);
        }
        
        if (wall.getWallObj().getBounds().getMaxY() < 5) {
            wall.getWallObj().setLocation(wall.getWallObj().getLocation().x, this.getSize().height-95);
        }
        
        if (wall.getWallObj().getBounds().getMinY() > this.getSize().height-90) {
            wall.getWallObj().setLocation(wall.getWallObj().getLocation().x, 2);
        }
        
        CommonCollisions();
    }
    
    private void CommonCollisions() {
        for (Wall wall : walls) {
            while (PlayerObj.getBounds().intersects(wall.getWallObj().getBounds())) {
                // Undo Last Move
                // Prevent Player From Moving If On Top Of Wall (Its A Feature Not A Bug)
                PlayerObj.setLocation(
                        PlayerObj.getLocation().x + playerInst.getDirLastMoved().x,
                        PlayerObj.getLocation().y + playerInst.getDirLastMoved().y
                );
            }
        }
    }
    
    // ==============================================================================
    
    public void SetCallback(IGameCallback callback) {
        this.callback = callback;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Game().setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EndGameMenuItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem GameHelpMenuItem;
    private javax.swing.JMenu GameMenu;
    private javax.swing.JMenuBar GameMenuBar;
    private javax.swing.JButton GoalObj;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JButton PlayerObj;
    private javax.swing.JMenuItem VersionMenuItem;
    private javax.swing.JButton WallObj1;
    private javax.swing.JButton WallObj2;
    private javax.swing.JButton WallObj3;
    private javax.swing.JButton WallObj4;
    private javax.swing.JButton WallObj5;
    private javax.swing.JButton WallObj6;
    private javax.swing.JButton WallObj7;
    private javax.swing.JButton WallObj8;
    private javax.swing.JMenuItem s20TimerMenuItem;
    private javax.swing.JMenuItem s40TimerMenuItem;
    private javax.swing.JMenuItem s60TimerMenuItem;
    // End of variables declaration//GEN-END:variables
}
